package com.nickcook.zeldex.ui.theme

import androidx.compose.ui.graphics.Color

val ZelDexPrimary = Color(0xFF006876)
val ZelDexOnPrimary = Color(0xFFFFFFFF)
val ZelDexPrimaryContainer = Color(0xFFA2EFFF)
val ZelDexOnPrimaryContainer = Color(0xFF001F25)
val ZelDexSecondary = Color(0xFF895100)
val ZelDexOnSecondary = Color(0xFFFFFFFF)
val ZelDexSecondaryContainer = Color(0xFFFFDCBC)
val ZelDexOnSecondaryContainer = Color(0xFF2C1700)
val ZelDexTertiary = Color(0xFF5B6400)
val ZelDexOnTertiary = Color(0xFFFFFFFF)
val ZelDexTertiaryContainer = Color(0xFFDFEB76)
val ZelDexOnTertiaryContainer = Color(0xFF1A1E00)
val ZelDexError = Color(0xFFBA1A1A)
val ZelDexErrorContainer = Color(0xFFFFDAD6)
val ZelDexOnError = Color(0xFFFFFFFF)
val ZelDexOnErrorContainer = Color(0xFF410002)
val ZelDexBackground = Color(0xFFFBFCFD)
val ZelDexOnBackground = Color(0xFF191C1D)
val ZelDexSurface = Color(0xFFFBFCFD)
val ZelDexOnSurface = Color(0xFF191C1D)
val ZelDexSurfaceVariant = Color(0xFFDBE4E7)
val ZelDexOnSurfaceVariant = Color(0xFF3F484A)
val ZelDexOutline = Color(0xFF6F797B)
val ZelDexInverseOnSurface = Color(0xFFEFF1F2)
val ZelDexInverseSurface = Color(0xFF2E3132)
val ZelDexInversePrimary = Color(0xFF51D7EF)
val ZelDexShadow = Color(0xFF000000)
val ZelDexSurfaceTint = Color(0xFF006876)
val ZelDexOutlineVariant = Color(0xFFBFC8CA)
val ZelDexScrim = Color(0xFF000000)

val ZelDexPrimaryDark = Color(0xFF51D7EF)
val ZelDexOnPrimaryDark = Color(0xFF00363E)
val ZelDexPrimaryContainerDark = Color(0xFF004E5A)
val ZelDexOnPrimaryContainerDark = Color(0xFFA2EFFF)
val ZelDexSecondaryDark = Color(0xFFFFB86B)
val ZelDexOnSecondaryDark = Color(0xFF492900)
val ZelDexSecondaryContainerDark = Color(0xFF683D00)
val ZelDexOnSecondaryContainerDark = Color(0xFFFFDCBC)
val ZelDexTertiaryDark = Color(0xFFC3CE5E)
val ZelDexOnTertiaryDark = Color(0xFF2E3300)
val ZelDexTertiaryContainerDark = Color(0xFF444B00)
val ZelDexOnTertiaryContainerDark = Color(0xFFDFEB76)
val ZelDexErrorDark = Color(0xFFFFB4AB)
val ZelDexErrorContainerDark = Color(0xFF93000A)
val ZelDexOnErrorDark = Color(0xFF690005)
val ZelDexOnErrorContainerDark = Color(0xFFFFDAD6)
val ZelDexBackgroundDark = Color(0xFF191C1D)
val ZelDexOnBackgroundDark = Color(0xFFE1E3E3)
val ZelDexSurfaceDark = Color(0xFF191C1D)
val ZelDexOnSurfaceDark = Color(0xFFE1E3E3)
val ZelDexSurfaceVariantDark = Color(0xFF3F484A)
val ZelDexOnSurfaceVariantDark = Color(0xFFBFC8CA)
val ZelDexOutlineDark = Color(0xFF899295)
val ZelDexInverseOnSurfaceDark = Color(0xFF191C1D)
val ZelDexInverseSurfaceDark = Color(0xFFE1E3E3)
val ZelDexInversePrimaryDark = Color(0xFF006876)
val ZelDexShadowDark = Color(0xFF000000)
val ZelDexSurfaceTintDark = Color(0xFF51D7EF)
val ZelDexOutlineVariantDark = Color(0xFF3F484A)
val ZelDexScrimDark = Color(0xFF000000)


val seed = Color(0xFF18ACC2)
